create extension if not exists vector;

create table if not exists public.knowledge_chunks (
  id bigint generated by default as identity primary key,
  source_name text not null,
  source_url text not null,
  document_title text,
  document_type text,
  section_title text,
  content text not null,
  content_hash text unique not null,
  chunk_index integer not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding vector(768) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists knowledge_chunks_source_url_idx on public.knowledge_chunks (source_url);
create index if not exists knowledge_chunks_content_hash_idx on public.knowledge_chunks (content_hash);
create index if not exists knowledge_chunks_embedding_hnsw_idx
  on public.knowledge_chunks using hnsw (embedding vector_cosine_ops);

alter table public.knowledge_chunks enable row level security;
revoke all on table public.knowledge_chunks from anon, authenticated;
grant select, insert, update, delete on table public.knowledge_chunks to service_role;
grant usage, select on sequence public.knowledge_chunks_id_seq to service_role;

create or replace function public.set_knowledge_chunks_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists knowledge_chunks_updated_at on public.knowledge_chunks;
create trigger knowledge_chunks_updated_at
before update on public.knowledge_chunks
for each row execute function public.set_knowledge_chunks_updated_at();

create or replace function public.match_knowledge_chunks(
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  source_name text,
  source_url text,
  document_title text,
  document_type text,
  section_title text,
  content text,
  content_hash text,
  metadata jsonb,
  similarity float
)
language sql stable
as $$
  select
    kc.id, kc.source_name, kc.source_url, kc.document_title, kc.document_type,
    kc.section_title, kc.content, kc.content_hash, kc.metadata,
    1 - (kc.embedding <=> query_embedding) as similarity
  from public.knowledge_chunks kc
  where 1 - (kc.embedding <=> query_embedding) >= match_threshold
  order by kc.embedding <=> query_embedding
  limit greatest(match_count, 0);
$$;

revoke all on function public.match_knowledge_chunks(vector, float, int) from public, anon, authenticated;
grant execute on function public.match_knowledge_chunks(vector, float, int) to service_role;

-- SUPABASE_SERVICE_ROLE_KEY is a backend/admin secret. Never expose it to a browser.
